### ISSUE TITLE
Use consistent gradle configurations

### ISSUE THREAD

**Issue by soberich** [spring-petclinic/spring-petclinic-kotlin#11]
Hi, 
Usage of `compile` and `runtime` deprecated,
also the project make usage of BOTH deprecated and "modern" configuration accessors which looks very inconsistent
e.g. both 
`testImplementation`, `testRuntimeOnly` 
and 
`runtime` and `compile`

**Comment by arey** [comment]
Thanks a lot @soberich for your remark. I've done some changes to use the modern syntax. Could you please check? ab01dd0
