### ISSUE TITLE
Superfluous @Param annotation on repository query methods

### ISSUE THREAD

**Issue by olivergierke** [spring-petclinic/spring-petclinic-kotlin#3]
The repositories use `@Param` to [explicitly declare](https://github.com/spring-petclinic/spring-petclinic-kotlin/blob/3e376fc529021c2a44ee235d6d5616ff4c95fe35/src/main/kotlin/org/springframework/samples/petclinic/owner/OwnerRepository.kt#L45) the query method parameter name. That shouldn't be necessary as with Kotlin they can be detected from the plain parameter.

**Comment by arey** [comment]
Thank you Oliver. Il will do the change.

**Comment by olivergierke** [comment]
Oh, interesting. I was expecting this to work OOTB as even Java 8 does that when compiling with `-parameters`. But thanks, Antoine.

**Comment by arey** [comment]
My JDK version is outdates (jdk1.8.0_25). Maybe default compiler option has changed in next versions?

**Comment by olivergierke** [comment]
Looks like [this commit](https://github.com/spring-projects/spring-boot/commit/0ba63424a759f5c76c78237ba54f815f4580a184#diff-edb0abc04bb3963027a99f413bb26bebR70) introduced the necessary setup. On previous Boot versions, I guess you'll have to manually enable that setting then.

**Comment by arey** [comment]
Nice. You find out the reason.
