### ISSUE TITLE
Generate the petclinic.css from less

### ISSUE THREAD

**Issue by arey** [spring-petclinic/spring-petclinic-kotlin#4]
The migration from Maven to Gradle #2 is not fully completed.
I temporary add the petclinic.css file. As in the maven build, the CSS should be generated from the less files.
Maven version of the Petclinic application is using the [wro4j-maven-plugin](https://github.com/spring-projects/spring-petclinic/blob/master/pom.xml).
There is a similar plugin fro gradle: [wro4j-gradle-plugin](https://github.com/IlyaAI/wro4j-gradle-plugin)

**Comment by luckymagic7** [comment]
Hi, did you solve the issue?
I want to compile petclinic.less into css, but no ideas..

**Comment by arey** [comment]
I didn't search, sorry

**Comment by luckymagic7** [comment]
That's OK. I'm just wondering why the [wro4j-gradle-plugin](https://github.com/IlyaAI/wro4j-gradle-plugin) doesn't work properly.

**Comment by arey** [comment]
Abandonned
