### ISSUE TITLE
Execution failed for task ':compileKotlin' on Windows 10

### ISSUE THREAD

**Issue by jamesjmtaylor** [spring-petclinic/spring-petclinic-kotlin#7]
I have a windows 10 OS that I tried executing `./gradlew bootRun`  immediately after cloning and received an OutOfMemoryError during compilation.  After doing some research I found that [this particular issue occurs on Windows machines](https://stackoverflow.com/a/747593/4520965) that have fairly austere memory allotments pre-allocated for Java application.  Is there any way around this, other than disabling my anti-virus?  My error log is attached below just in case I misinterpreted it.  

[logsError.txt](https://github.com/spring-petclinic/spring-petclinic-kotlin/files/1633375/logsError.txt)

**Comment by arey** [comment]
I don't see the OutOfMemoryError stackstrace in your attached logsError.txt file. Any idea?

Do you have tried to temporary disable your Antivirus to check if it solves your problem.

**Comment by jamesjmtaylor** [comment]
My mistake, that was just a daemon option.  I tried running it with anti-virus disabled and received the same result.  I've attached the output for --info and --
stacktrace below.  I've also included a screenshot of  the terminal: 

![capture](https://user-images.githubusercontent.com/17860994/34990294-78519c4a-fa7a-11e7-94e0-c993903bbe0b.JPG)

Whats weird is that a test Kotlin app that I made in Android Studio on the same system compiles and runs fine, so I don't know why I'd receive an error in the terminal for "Execution failed for task ':compileKotlin'"

[info.txt](https://github.com/spring-petclinic/spring-petclinic-kotlin/files/1635145/info.txt)
[stacktrace.txt](https://github.com/spring-petclinic/spring-petclinic-kotlin/files/1635147/stacktrace.txt)

**Comment by jamesjmtaylor** [comment]
It runs fine on my macbook :) just not Windows 10.  I was looking through Docker Hub and it appears that there are images for spring-petclinic, but none for spring-petclinic-kotlin.  Do you have any plans of releasing one soon so that I could try that?  If a dockerized version doesn't run then something would have to be really wrong with my system.

**Comment by arey** [comment]
Having a Docker image for spring-petclinic-kotlin could be plan. I add it to our roadmap.

By waiting, I've tested the application on a Windows 7 Entreprise SP1 64 bits and and JDK 1.8.0_73. It works fine. I will test on a Windows 10 VM.
Wich JDK version are you using ? Is it the same between your Macbook and Windows.

**Comment by jamesjmtaylor** [comment]
I'm using java version "1.8.0_111" on my MacBook. I'm at work so I can't comment yet on my Windows version.  I might tinker on creating a Dockerized version if you've got more pressing stuff on your plate at the moment.

**Comment by arey** [comment]
I've just tried on a Windows 10 64 bits VM and a JDK version 1.8.0_71 and it runs fine. I'm sorry.

**Comment by jamesjmtaylor** [comment]
So... I successfully built a docker container for the kotlin web client and included it in the docker-compose file.  But when I try to run it I receive the error `Task 'bootRun' not found in root project 'gradle'.`  I think I'm pretty close, but I've spent the last couple hours trying to figure out where to go from here and haven't met with much success.  You can see my code [here](https://github.com/jamesjmtaylor/spring-petclinic-kotlin-dockerized).  If we're able to figure it out I'll create a branch from your branch and do a legitimate PR, rather than the pseudo-fork that I have now.

**Comment by arey** [comment]
Hi @jamesjmtaylor. Do you find a solution to your issue?

**Comment by jamesjmtaylor** [comment]
Negative, but you can close the issue.  Probably something on my end with my Windows machine.

**Comment by arey** [comment]
Ok thanks for the feedback.
